name = "Moondial"
author = "illuc"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b27962b8b9ff5d4315d094e433ddcc9462bbf8a14a7c3d0211a7ffc42347f7e"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
