name = "Moondial"
author = "illuc"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a462c944af3541de520d231ff92544319b8cf29cfad246a7cfc8c914a09abf6"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
