name = "Moondial"
author = "illuc"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "208bb0d489f20b6ab7c738907843c5220c892ea8ef7a77d18145a83b449cc69f"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
