name = "Moondial"
author = "illuc"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba026d9fef308d900c1101b490810ef48c4a8d4d1859bd0929828f5f98c6dd93"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
